# Generated by Django 4.1.2 on 2022-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(max_length=8, verbose_name='Id Producto')),
                ('productName', models.CharField(max_length=70, verbose_name='Nombre Producto')),
                ('productLine', models.CharField(max_length=25, verbose_name='Línea Producto')),
                ('choice_productLine', models.CharField(choices=[('1', 'Autos Clásicos'), ('2', 'Motocicletas'), ('3', 'Aviones'), ('4', 'Barcos'), ('5', 'Trenes'), ('6', 'Camiones y Colectivos'), ('7', 'Autos Antiguos')], max_length=1, verbose_name='Línea Elegida Producto')),
                ('productScale', models.CharField(max_length=10, verbose_name='Escala Producto')),
                ('productVendor', models.CharField(max_length=30, verbose_name='Proveedor Producto')),
                ('productDescription', models.CharField(max_length=400, verbose_name='Descripción Producto')),
                ('quantity', models.IntegerField(verbose_name='Stock Producto')),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de Compra Producto')),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de Venta Sugerido Producto')),
            ],
        ),
    ]
